
export const types = Object.freeze({
   FILTER_SET_CONTACTS: 'FILTER_SET_CONTACTS',
   FILTER_SET_SEARCH_TERM: 'FILTER_SET_SEARCH_TERM',
   FILTER_SET_GENDER: 'FILTER_SET_GENDER',
   FILTER_SET_NATIONALITY: 'FILTER_SET_NATIONALITY',
   FILTER_SET_ISCREATOR: 'FILTER_SET_ISCREATOR',
   FILTER_CLEAR: 'FILTER_CLEAR',
})