
export const types = Object.freeze({
   AUTH_START_FETCHING: 'AUTH_START_FETCHING',
   AUTH_STOP_FETCHING: 'AUTH_STOP_FETCHING',
   AUTH_OPEN_MODAL: 'AUTH_OPEN_MODAL',
   AUTH_CLOSE_MODAL: 'AUTH_CLOSE_MODAL',
   AUTH_FETCH_DATA: 'AUTH_FETCH_DATA',
   AUTH_SET_AUTHORIZED: 'AUTH_SET_AUTHORIZED',
});