
export const types = Object.freeze({
   CONTACTS_FETCH_CONTACTS: 'CONTACTS_FETCH_CONTACTS',
   CONTACTS_START_FETCHING: 'CONTACTS_START_FETCHING',
   CONTACTS_STOP_FETCHING: 'CONTACTS_STOP_FETCHING',
   CONTACTS_ERROR_FETCHING: 'CONTACTS_ERROR_FETCHING',
   CONTACTS_SET_TABLE_CURRENT_PAGE: 'CONTACTS_SET_TABLE_CURRENT_PAGE',
   CONTACTS_SET_TABLE_PAGE_SIZE: 'CONTACTS_SET_TABLE_PAGE_SIZE',
   CONTACTS_SET_TILED_CURRENT_PAGE: 'CONTACTS_SET_TILED_CURRENT_PAGE',
   CONTACTS_SET_TILED_PAGE_SIZE: 'CONTACTS_SET_TILED_PAGE_SIZE',
   CONTACTS_SET_SORT_ORDER: 'CONTACTS_SET_SORT_ORDER',
})