
export const types = Object.freeze({
   CONTACTS_FETCH_CONTACTS: 'CONTACTS_FETCH_CONTACTS',
   CONTACTS_START_FETCHING: 'CONTACTS_START_FETCHING',
   CONTACTS_STOP_FETCHING: 'CONTACTS_STOP_FETCHING',
})